version: '3'

services:

    atheos-ide:
        image: hlsiira/atheos:latest
        container_name: ${CONTAINER_NAME:-atheos-ide}
        networks:
          - default
        volumes:
          - ${APP_HTML_PATH}:/var/www/html:rw
        environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST}
          - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
          - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
    default:
        external:
            name: ${NETWORK}