version: '3'

services:
    
    teamspeak-db:
        image: mariadb
        container_name: ${DB_CONTAINER_NAME}
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${TS3_DB_ROOT_PASSWORD}
            MYSQL_DATABASE: teamspeak
        volumes:
            - ${DB_DATA_PATH}:/var/lib/mysql/

    teamspeak:
        image: teamspeak
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        depends_on: 
            - teamspeak-db
        ports:
            - 9987:9987/udp
            - 10011:10011
            - 30033:30033
        environment:
            TS3SERVER_DB_PLUGIN: ts3db_mariadb
            TS3SERVER_DB_SQLCREATEPATH: create_mariadb
            TS3SERVER_DB_HOST: teamspeak-db
            TS3SERVER_DB_USER: root
            TS3SERVER_DB_PASSWORD: ${TS3_DB_ROOT_PASSWORD}
            TS3SERVER_DB_NAME: teamspeak
            TS3SERVER_DB_WAITUNTILREADY: 30
            TS3SERVER_LICENSE: accept
        volumes:
            - ${APP_DATA_PATH}:/var/ts3server/