version: '3'

services:
    gitlab-app:
        image: gitlab/gitlab-ce:latest
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        hostname: ${VIRTUAL_HOST}
        volumes:
            - ${GITLAB_DATA_PATH}:/var/opt/gitlab
            - ${GITLAB_CONFIG_PATH}:/etc/gitlab
            - ${GITLAB_LOGS_PATH}:/var/log/gitlab
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            GITLAB_OMNIBUS_CONFIG: ${GITLAB_OMNIBUS_CONFIG}
        networks:
            - default

networks:
    default:
        external:
            name: ${NETWORK}